all_tiles = [
{'type': 5, 'id': 0, 'neighbor_list': [{'neighbor_id': 1}]},
{'type': 7, 'id': 1, 'neighbor_list': [{'neighbor_id': 2}]},
{'type': 2, 'id': 2, 'neighbor_list': [{'neighbor_id': 3}]},
{'type': 4, 'id': 3, 'neighbor_list': [{'neighbor_id': 4}]},
{'type': 9, 'id': 4, 'neighbor_list': [{'neighbor_id': 5}]},
{'type': 9, 'id': 5, 'neighbor_list': [{'neighbor_id': 6}]},
{'type': 4, 'id': 6, 'neighbor_list': [{'neighbor_id': 7}]},
{'type': 7, 'id': 7, 'neighbor_list': [{'neighbor_id': 8}]},
{'type': 5, 'id': 8, 'neighbor_list': [{'neighbor_id': 9}]},
{'type': 9, 'id': 9, 'neighbor_list': [{'neighbor_id': 27}]},
{'type': 'E', 'id': 999, 'neighbor_list': []},
{'type': 'E', 'id': 999, 'neighbor_list': []},
{'type': 6, 'id': 12, 'neighbor_list': [{'neighbor_id': 13}]},
{'type': 3, 'id': 13, 'neighbor_list': [{'neighbor_id': 14}]},
{'type': 2, 'id': 14, 'neighbor_list': [{'neighbor_id': 15}, {'neighbor_id': 32}]},
{'type': 5, 'id': 15, 'neighbor_list': [{'neighbor_id': 16}]},
{'type': 7, 'id': 16, 'neighbor_list': [{'neighbor_id': 34}]},
{'type': 'E', 'id': 999, 'neighbor_list': []},
{'type': 1, 'id': 18, 'neighbor_list': [{'neighbor_id': 0}]},
{'type': 'E', 'id': 999, 'neighbor_list': []},
{'type': 'E', 'id': 999, 'neighbor_list': []},
{'type': 'E', 'id': 999, 'neighbor_list': []},
{'type': 7, 'id': 22, 'neighbor_list': [{'neighbor_id': 4}]},
{'type': 'E', 'id': 999, 'neighbor_list': []},
{'type': 'E', 'id': 999, 'neighbor_list': []},
{'type': 'E', 'id': 999, 'neighbor_list': []},
{'type': 'E', 'id': 999, 'neighbor_list': []},
{'type': 9, 'id': 27, 'neighbor_list': [{'neighbor_id': 28}]},
{'type': 8, 'id': 28, 'neighbor_list': [{'neighbor_id': 29}]},
{'type': 8, 'id': 29, 'neighbor_list': [{'neighbor_id': 30}]},
{'type': 4, 'id': 30, 'neighbor_list': [{'neighbor_id': 12}]},
{'type': 'E', 'id': 999, 'neighbor_list': []},
{'type': 5, 'id': 32, 'neighbor_list': [{'neighbor_id': 50}]},
{'type': 'E', 'id': 999, 'neighbor_list': []},
{'type': 5, 'id': 34, 'neighbor_list': [{'neighbor_id': 52}]},
{'type': 'E', 'id': 999, 'neighbor_list': []},
{'type': 'X', 'id': 36, 'neighbor_list': [{'neighbor_id': 18}]},
{'type': 'E', 'id': 999, 'neighbor_list': []},
{'type': 'E', 'id': 999, 'neighbor_list': []},
{'type': 'E', 'id': 999, 'neighbor_list': []},
{'type': 4, 'id': 40, 'neighbor_list': [{'neighbor_id': 22}]},
{'type': 'E', 'id': 999, 'neighbor_list': []},
{'type': 'E', 'id': 999, 'neighbor_list': []},
{'type': 'E', 'id': 999, 'neighbor_list': []},
{'type': 'E', 'id': 999, 'neighbor_list': []},
{'type': 'E', 'id': 999, 'neighbor_list': []},
{'type': 'E', 'id': 999, 'neighbor_list': []},
{'type': 'E', 'id': 999, 'neighbor_list': []},
{'type': 'E', 'id': 999, 'neighbor_list': []},
{'type': 'E', 'id': 999, 'neighbor_list': []},
{'type': 2, 'id': 50, 'neighbor_list': [{'neighbor_id': 68}]},
{'type': 'E', 'id': 999, 'neighbor_list': []},
{'type': 7, 'id': 52, 'neighbor_list': [{'neighbor_id': 70}]},
{'type': 'E', 'id': 999, 'neighbor_list': []},
{'type': 7, 'id': 54, 'neighbor_list': [{'neighbor_id': 36}]},
{'type': 'E', 'id': 999, 'neighbor_list': []},
{'type': 'E', 'id': 999, 'neighbor_list': []},
{'type': 'E', 'id': 999, 'neighbor_list': []},
{'type': 1, 'id': 58, 'neighbor_list': [{'neighbor_id': 76}, {'neighbor_id': 40}]},
{'type': 3, 'id': 59, 'neighbor_list': [{'neighbor_id': 58}]},
{'type': 4, 'id': 60, 'neighbor_list': [{'neighbor_id': 59}]},
{'type': 3, 'id': 61, 'neighbor_list': [{'neighbor_id': 62}, {'neighbor_id': 60}]},
{'type': 7, 'id': 62, 'neighbor_list': [{'neighbor_id': 63}]},
{'type': 'B', 'id': 63, 'neighbor_list': [{'neighbor_id': 64}]},
{'type': 9, 'id': 64, 'neighbor_list': [{'neighbor_id': 65}]},
{'type': 1, 'id': 65, 'neighbor_list': [{'neighbor_id': 66}]},
{'type': 2, 'id': 66, 'neighbor_list': [{'neighbor_id': 67}]},
{'type': 7, 'id': 67, 'neighbor_list': [{'neighbor_id': 68}]},
{'type': 3, 'id': 68, 'neighbor_list': [{'neighbor_id': 86}]},
{'type': 'E', 'id': 999, 'neighbor_list': []},
{'type': 8, 'id': 70, 'neighbor_list': [{'neighbor_id': 88}]},
{'type': 'E', 'id': 999, 'neighbor_list': []},
{'type': 8, 'id': 72, 'neighbor_list': [{'neighbor_id': 54}]},
{'type': 'E', 'id': 999, 'neighbor_list': []},
{'type': 'E', 'id': 999, 'neighbor_list': []},
{'type': 'E', 'id': 999, 'neighbor_list': []},
{'type': 3, 'id': 76, 'neighbor_list': [{'neighbor_id': 94}]},
{'type': 'E', 'id': 999, 'neighbor_list': []},
{'type': 'E', 'id': 999, 'neighbor_list': []},
{'type': 6, 'id': 79, 'neighbor_list': [{'neighbor_id': 61}]},
{'type': 'E', 'id': 999, 'neighbor_list': []},
{'type': 'E', 'id': 999, 'neighbor_list': []},
{'type': 'E', 'id': 999, 'neighbor_list': []},
{'type': 'E', 'id': 999, 'neighbor_list': []},
{'type': 'E', 'id': 999, 'neighbor_list': []},
{'type': 'E', 'id': 999, 'neighbor_list': []},
{'type': 8, 'id': 86, 'neighbor_list': [{'neighbor_id': 87}]},
{'type': 1, 'id': 87, 'neighbor_list': [{'neighbor_id': 88}]},
{'type': 4, 'id': 88, 'neighbor_list': [{'neighbor_id': 106}]},
{'type': 'E', 'id': 999, 'neighbor_list': []},
{'type': 8, 'id': 90, 'neighbor_list': [{'neighbor_id': 72}]},
{'type': 'E', 'id': 999, 'neighbor_list': []},
{'type': 'E', 'id': 999, 'neighbor_list': []},
{'type': 2, 'id': 93, 'neighbor_list': [{'neighbor_id': 111}]},
{'type': 8, 'id': 94, 'neighbor_list': [{'neighbor_id': 93}]},
{'type': 'E', 'id': 999, 'neighbor_list': []},
{'type': 'E', 'id': 999, 'neighbor_list': []},
{'type': 2, 'id': 97, 'neighbor_list': [{'neighbor_id': 79}]},
{'type': 'E', 'id': 999, 'neighbor_list': []},
{'type': 'E', 'id': 999, 'neighbor_list': []},
{'type': 'E', 'id': 999, 'neighbor_list': []},
{'type': 'E', 'id': 999, 'neighbor_list': []},
{'type': 'E', 'id': 999, 'neighbor_list': []},
{'type': 'E', 'id': 999, 'neighbor_list': []},
{'type': 'E', 'id': 999, 'neighbor_list': []},
{'type': 'E', 'id': 999, 'neighbor_list': []},
{'type': 'X', 'id': 106, 'neighbor_list': [{'neighbor_id': 124}]},
{'type': 'E', 'id': 999, 'neighbor_list': []},
{'type': 9, 'id': 108, 'neighbor_list': [{'neighbor_id': 90}]},
{'type': 1, 'id': 109, 'neighbor_list': [{'neighbor_id': 108}]},
{'type': 'O', 'id': 110, 'neighbor_list': [{'neighbor_id': 109}]},
{'type': 5, 'id': 111, 'neighbor_list': [{'neighbor_id': 110}]},
{'type': 'E', 'id': 999, 'neighbor_list': []},
{'type': 'E', 'id': 999, 'neighbor_list': []},
{'type': 'E', 'id': 999, 'neighbor_list': []},
{'type': 4, 'id': 115, 'neighbor_list': [{'neighbor_id': 116}, {'neighbor_id': 97}]},
{'type': 3, 'id': 116, 'neighbor_list': [{'neighbor_id': 117}]},
{'type': 1, 'id': 117, 'neighbor_list': [{'neighbor_id': 118}]},
{'type': 4, 'id': 118, 'neighbor_list': [{'neighbor_id': 119}]},
{'type': 6, 'id': 119, 'neighbor_list': [{'neighbor_id': 120}]},
{'type': 3, 'id': 120, 'neighbor_list': [{'neighbor_id': 121}]},
{'type': 2, 'id': 121, 'neighbor_list': [{'neighbor_id': 122}]},
{'type': 9, 'id': 122, 'neighbor_list': [{'neighbor_id': 123}]},
{'type': 1, 'id': 123, 'neighbor_list': [{'neighbor_id': 124}]},
{'type': 4, 'id': 124, 'neighbor_list': [{'neighbor_id': 142}]},
{'type': 'E', 'id': 999, 'neighbor_list': []},
{'type': 5, 'id': 126, 'neighbor_list': [{'neighbor_id': 108}]},
{'type': 'E', 'id': 999, 'neighbor_list': []},
{'type': 'E', 'id': 999, 'neighbor_list': []},
{'type': 'E', 'id': 999, 'neighbor_list': []},
{'type': 'E', 'id': 999, 'neighbor_list': []},
{'type': 'E', 'id': 999, 'neighbor_list': []},
{'type': 8, 'id': 132, 'neighbor_list': [{'neighbor_id': 133}]},
{'type': 7, 'id': 133, 'neighbor_list': [{'neighbor_id': 115}]},
{'type': 'E', 'id': 999, 'neighbor_list': []},
{'type': 'E', 'id': 999, 'neighbor_list': []},
{'type': 'E', 'id': 999, 'neighbor_list': []},
{'type': 'E', 'id': 999, 'neighbor_list': []},
{'type': 'E', 'id': 999, 'neighbor_list': []},
{'type': 6, 'id': 139, 'neighbor_list': [{'neighbor_id': 121}]},
{'type': 'E', 'id': 999, 'neighbor_list': []},
{'type': 'E', 'id': 999, 'neighbor_list': []},
{'type': 7, 'id': 142, 'neighbor_list': [{'neighbor_id': 160}]},
{'type': 'E', 'id': 999, 'neighbor_list': []},
{'type': 5, 'id': 144, 'neighbor_list': [{'neighbor_id': 126}]},
{'type': 'E', 'id': 999, 'neighbor_list': []},
{'type': 'E', 'id': 999, 'neighbor_list': []},
{'type': 'E', 'id': 999, 'neighbor_list': []},
{'type': 'E', 'id': 999, 'neighbor_list': []},
{'type': 1, 'id': 149, 'neighbor_list': [{'neighbor_id': 150}]},
{'type': 2, 'id': 150, 'neighbor_list': [{'neighbor_id': 132}]},
{'type': 'E', 'id': 999, 'neighbor_list': []},
{'type': 'E', 'id': 999, 'neighbor_list': []},
{'type': 'E', 'id': 999, 'neighbor_list': []},
{'type': 'E', 'id': 999, 'neighbor_list': []},
{'type': 'E', 'id': 999, 'neighbor_list': []},
{'type': 1, 'id': 156, 'neighbor_list': [{'neighbor_id': 157}]},
{'type': 8, 'id': 157, 'neighbor_list': [{'neighbor_id': 139}]},
{'type': 'E', 'id': 999, 'neighbor_list': []},
{'type': 'E', 'id': 999, 'neighbor_list': []},
{'type': 4, 'id': 160, 'neighbor_list': [{'neighbor_id': 178}]},
{'type': 'E', 'id': 999, 'neighbor_list': []},
{'type': 9, 'id': 162, 'neighbor_list': [{'neighbor_id': 144}]},
{'type': 'E', 'id': 999, 'neighbor_list': []},
{'type': 'E', 'id': 999, 'neighbor_list': []},
{'type': 'E', 'id': 999, 'neighbor_list': []},
{'type': 'E', 'id': 999, 'neighbor_list': []},
{'type': 5, 'id': 167, 'neighbor_list': [{'neighbor_id': 149}]},
{'type': 'E', 'id': 999, 'neighbor_list': []},
{'type': 'E', 'id': 999, 'neighbor_list': []},
{'type': 'E', 'id': 999, 'neighbor_list': []},
{'type': 'E', 'id': 999, 'neighbor_list': []},
{'type': 'E', 'id': 999, 'neighbor_list': []},
{'type': 'E', 'id': 999, 'neighbor_list': []},
{'type': 6, 'id': 174, 'neighbor_list': [{'neighbor_id': 156}]},
{'type': 'E', 'id': 999, 'neighbor_list': []},
{'type': 'E', 'id': 999, 'neighbor_list': []},
{'type': 'E', 'id': 999, 'neighbor_list': []},
{'type': 7, 'id': 178, 'neighbor_list': [{'neighbor_id': 196}]},
{'type': 'E', 'id': 999, 'neighbor_list': []},
{'type': 4, 'id': 180, 'neighbor_list': [{'neighbor_id': 162}]},
{'type': 'E', 'id': 999, 'neighbor_list': []},
{'type': 'E', 'id': 999, 'neighbor_list': []},
{'type': 'E', 'id': 999, 'neighbor_list': []},
{'type': 'E', 'id': 999, 'neighbor_list': []},
{'type': 5, 'id': 185, 'neighbor_list': [{'neighbor_id': 167}]},
{'type': 'E', 'id': 999, 'neighbor_list': []},
{'type': 'E', 'id': 999, 'neighbor_list': []},
{'type': 'E', 'id': 999, 'neighbor_list': []},
{'type': 'E', 'id': 999, 'neighbor_list': []},
{'type': 'E', 'id': 999, 'neighbor_list': []},
{'type': 'E', 'id': 999, 'neighbor_list': []},
{'type': 2, 'id': 192, 'neighbor_list': [{'neighbor_id': 174}]},
{'type': 'E', 'id': 999, 'neighbor_list': []},
{'type': 'E', 'id': 999, 'neighbor_list': []},
{'type': 'E', 'id': 999, 'neighbor_list': []},
{'type': 6, 'id': 196, 'neighbor_list': [{'neighbor_id': 214}]},
{'type': 'E', 'id': 999, 'neighbor_list': []},
{'type': 8, 'id': 198, 'neighbor_list': [{'neighbor_id': 180}]},
{'type': 5, 'id': 199, 'neighbor_list': [{'neighbor_id': 198}]},
{'type': 5, 'id': 200, 'neighbor_list': [{'neighbor_id': 199}]},
{'type': 6, 'id': 201, 'neighbor_list': [{'neighbor_id': 200}]},
{'type': 3, 'id': 202, 'neighbor_list': [{'neighbor_id': 201}]},
{'type': 1, 'id': 203, 'neighbor_list': [{'neighbor_id': 202}, {'neighbor_id': 185}]},
{'type': 6, 'id': 204, 'neighbor_list': [{'neighbor_id': 203}]},
{'type': 9, 'id': 205, 'neighbor_list': [{'neighbor_id': 204}]},
{'type': 1, 'id': 206, 'neighbor_list': [{'neighbor_id': 205}]},
{'type': 9, 'id': 207, 'neighbor_list': [{'neighbor_id': 206}]},
{'type': 7, 'id': 208, 'neighbor_list': [{'neighbor_id': 207}]},
{'type': 'O', 'id': 209, 'neighbor_list': [{'neighbor_id': 208}]},
{'type': 1, 'id': 210, 'neighbor_list': [{'neighbor_id': 207}, {'neighbor_id': 192}]},
{'type': 6, 'id': 211, 'neighbor_list': [{'neighbor_id': 210}]},
{'type': 'B', 'id': 212, 'neighbor_list': [{'neighbor_id': 211}]},
{'type': 6, 'id': 213, 'neighbor_list': [{'neighbor_id': 212}]},
{'type': 5, 'id': 214, 'neighbor_list': [{'neighbor_id': 213}]},
{'type': 'S', 'id': 215, 'neighbor_list': [{'neighbor_id': 214}]}]